In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import nltk
import pickle

In [2]:
df = pd.read_csv('/content/spam_sms_dataset.csv')
df.head()

      LABEL                                               TEXT URL EMAIL PHONE
0       ham  Your opinion about me? 1. Over 2. Jada 3. Kusr...  No    No    No
1       ham  What's up? Do you want me to come online? If y...  No    No    No
2       ham                       So u workin overtime nigpun?  No    No    No
3       ham  Also sir, i sent you an email about how to log...  No    No    No
4  Smishing  Please Stay At Home. To encourage the notion o...  No    No    No

In [3]:
df["LABEL"] = df["LABEL"].str.lower()

In [4]:
df["LABEL"].unique()

array(['ham', 'smishing', 'spam'], dtype=object)

In [5]:
#converting columns from text to numbers using label encoder

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["LABEL"] = le.fit_transform(df["LABEL"])

In [6]:
df["LABEL"].unique()

array([0, 1, 2])

In [7]:
df["PHONE"] = df["PHONE"].replace({"yes":1,"No":0})
df["PHONE"].unique()

<ipython-input-7-776a94398d5a>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["PHONE"] = df["PHONE"].replace({"yes":1,"No":0})

array([0, 1])

In [8]:
df["EMAIL"] = df["EMAIL"].replace({"yes":1,"No":0})
df["EMAIL"].unique()

<ipython-input-8-3f209b00f9df>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["EMAIL"] = df["EMAIL"].replace({"yes":1,"No":0})

array([0, 1])

In [9]:
df["URL"] = df["URL"].replace({"yes":1,"No":0})
df["URL"].unique()

<ipython-input-9-53ffcb628476>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["URL"] = df["URL"].replace({"yes":1,"No":0})

array([0, 1])

In [10]:
df.sample(n=5)

,LABEL,TEXT,URL,EMAIL,PHONE
29,0,Whens your radio show?,0,0,0
2330,0,Hey sexy buns! What of that day? No word from ...,0,0,0
1348,0,Me i'm not workin. Once i get job...,0,0,0
5189,0,"Hey, iouri gave me your number, I'm wylie, rya...",0,0,0
4319,0,I donno its in your genes or something,0,0,0

In [11]:
#lowering the text
df["TEXT"] = df["TEXT"].str.lower()

In [12]:
import re

In [13]:
def remove_specific_numbers(text):
    # Regular expression to match 4- to 12-digit numbers
    number_pattern = re.compile(r'\b\d{4,12}\b')
    return number_pattern.sub(r'', text)

In [14]:
with open('remove_specific_numbers.pkl', 'wb') as file:
    pickle.dump(remove_specific_numbers, file)

In [15]:
df["TEXT"] = df["TEXT"].apply(remove_specific_numbers)

In [16]:
def remove_specific_emails(text):
  email_pattern = re.compile(r'\b[A-Za-z0-9._%+-]+@(gmail\.com|hotmail\.com|kiefer\.com|emc\.co\.uk|.co\.uk)\b')
  return email_pattern.sub(r'', text)

In [17]:
df['TEXT'] = df['TEXT'].apply(remove_specific_emails)

In [18]:
with open('remove_specific_emails.pkl', 'wb') as file:
    pickle.dump(remove_specific_emails, file)

In [19]:
df["HTTP"] =0
df["HTTPS"]=0
df["BIT"]=0
df["WWW"]=0

In [20]:
def update_link_flags(row):
    http_pattern = re.compile(r'http://\S+')
    https_pattern = re.compile(r'https://\S+')
    bit_pattern = re.compile(r'bit\.\S+')
    www_pattern = re.compile(r'www\.\S+')

    # Check and update the corresponding columns
    if http_pattern.search(row['TEXT']):
        row['HTTP'] = 1
    if https_pattern.search(row['TEXT']):
        row['HTTPS'] = 1
    if bit_pattern.search(row['TEXT']):
        row['BIT'] = 1
    if www_pattern.search(row['TEXT']):
        row['WWW'] = 1

    return row

In [21]:
df = df.apply(update_link_flags,axis =1)

In [22]:

with open('update_link_flags.pkl', 'wb') as file:
    pickle.dump(update_link_flags, file)

In [23]:
import string
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [24]:
from nltk.stem import WordNetLemmatizer
lm =  WordNetLemmatizer()

In [25]:
def process_text(text):
    text = nltk.word_tokenize(text)
    #removing special charcters
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)

    text = y[:]
    y.clear()
  #removing stop words
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)

    text = y[:]
    y.clear()
    #lemmatization
    for i in text:
        y.append(lm.lemmatize(i))
    return " ".join(y)

In [26]:
df["text_processed"] = df["TEXT"].apply(process_text)

In [27]:
with open('process_text.pkl', 'wb') as file:
    pickle.dump(process_text, file)

In [28]:
df["TEXT"][4]

'please stay at home. to encourage the notion of staying at home. all tax-paying citizens are entitled to �305.96 or more emergency refund. smsg.io/fcvbd'

In [29]:
df.head()

,LABEL,TEXT,URL,EMAIL,PHONE,HTTP,HTTPS,BIT,WWW,text_processed
0,0,your opinion about me? 1. over 2. jada 3. kusr...,0,0,0,0,0,0,0,opinion jada kusruthi lovable silent spl chara...
1,0,what's up? do you want me to come online? if y...,0,0,0,0,0,0,0,want come online free talk
2,0,so u workin overtime nigpun?,0,0,0,0,0,0,0,u workin overtime nigpun
3,0,"also sir, i sent you an email about how to log...",0,0,0,0,0,0,0,also sir sent email log usc payment portal sen...
4,1,please stay at home. to encourage the notion o...,0,0,0,0,0,0,0,please stay home encourage notion staying home...

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
tf = TfidfVectorizer(max_features = 3000)

In [32]:
vec = tf.fit_transform(df["text_processed"]).toarray()

In [33]:
with open('vectorizer.pkl', 'wb') as file:
    pickle.dump(tf, file)

In [34]:
y = df["LABEL"].values

In [35]:
vec = pd.DataFrame(vec)

In [36]:
X = pd.concat([df,vec],axis =1)

In [37]:
X.drop(["TEXT","text_processed","LABEL"],axis=1,inplace = True)

In [38]:
X.head()

,URL,EMAIL,PHONE,HTTP,HTTPS,BIT,WWW,0,1,2,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
0,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
X= X.rename(columns={"URL":3000,"EMAIL":3001,"PHONE":3002,"HTTP":3003,"HTTPS":3004,"BIT":3005,"WWW":3006})

In [40]:
X.head()

,3000,3001,3002,3003,3004,3005,3006,0,1,2,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
0,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [42]:
pip install imbalanced-learn scikit-learn

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.10/dist-packages (0.12.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.5.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from imbalanced-learn) (3.5.0)

In [43]:
from imblearn.combine import SMOTEENN

In [44]:
smoteen = SMOTEENN(random_state=42)

In [45]:
X_resampled, y_resampled = smoteen.fit_resample(X_train, y_train)

In [46]:
with open('smoteen.pkl', 'wb') as file:
    pickle.dump(smoteen, file)

In [47]:
X_resampled.head()

,3000,3001,3002,3003,3004,3005,3006,0,1,2,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
0,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,0,0,0,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [48]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB

In [49]:
gb = GaussianNB()
mb = MultinomialNB()
bb = BernoulliNB()

In [50]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
lr = LogisticRegression()

In [53]:
lr.fit(X_resampled,y_resampled)
y_pred = lr.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9539748953974896
[[935   1   4]
 [  3 124  20]
 [ 10  17  81]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       940
           1       0.87      0.84      0.86       147
           2       0.77      0.75      0.76       108

    accuracy                           0.95      1195
   macro avg       0.88      0.86      0.87      1195
weighted avg       0.95      0.95      0.95      1195

In [54]:
gb.fit(X_resampled,y_resampled)
y_pred = lr.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9539748953974896
[[935   1   4]
 [  3 124  20]
 [ 10  17  81]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       940
           1       0.87      0.84      0.86       147
           2       0.77      0.75      0.76       108

    accuracy                           0.95      1195
   macro avg       0.88      0.86      0.87      1195
weighted avg       0.95      0.95      0.95      1195

In [55]:
model = mb.fit(X_resampled,y_resampled)
y_pred = mb.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9347280334728033
[[910  11  19]
 [  1 120  26]
 [  5  16  87]]
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       940
           1       0.82      0.82      0.82       147
           2       0.66      0.81      0.72       108

    accuracy                           0.93      1195
   macro avg       0.82      0.86      0.84      1195
weighted avg       0.94      0.93      0.94      1195

In [56]:
with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)

In [57]:
bb.fit(X_resampled,y_resampled)
y_pred = lr.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9539748953974896
[[935   1   4]
 [  3 124  20]
 [ 10  17  81]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       940
           1       0.87      0.84      0.86       147
           2       0.77      0.75      0.76       108

    accuracy                           0.95      1195
   macro avg       0.88      0.86      0.87      1195
weighted avg       0.95      0.95      0.95      1195

In [58]:
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier()

In [59]:
et.fit(X_resampled,y_resampled)
y_pred = lr.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9539748953974896
[[935   1   4]
 [  3 124  20]
 [ 10  17  81]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       940
           1       0.87      0.84      0.86       147
           2       0.77      0.75      0.76       108

    accuracy                           0.95      1195
   macro avg       0.88      0.86      0.87      1195
weighted avg       0.95      0.95      0.95      1195

In [60]:

# Load all components
with open('remove_specific_numbers.pkl', 'rb') as file:
    remove_specific_numbers = pickle.load(file)

with open('remove_specific_emails.pkl', 'rb') as file:
    remove_specific_emails = pickle.load(file)

with open('update_link_flags.pkl', 'rb') as file:
    update_link_flags = pickle.load(file)

with open('process_text.pkl', 'rb') as file:
    process_text = pickle.load(file)

with open('vectorizer.pkl', 'rb') as file:
    vectorizer = pickle.load(file)

with open('smoteen.pkl', 'rb') as file:
    smoteen = pickle.load(file)

with open('model.pkl', 'rb') as file:
    model = pickle.load(file)

In [61]:
def preprocess_new_text(input_text):
    input_text = input_text.lower()
    input_text = remove_specific_numbers(input_text)
    input_text = remove_specific_emails(input_text)
    input_text_processed = process_text(input_text)
    X_input_text = tf.transform([input_text_processed]).toarray()

    flags = {'TEXT': input_text, 'URL': 0, 'EMAIL': 0, 'PHONE': 0, 'HTTP': 0, 'HTTPS': 0, 'BIT': 0, 'WWW': 0}
    flags = update_link_flags(flags)

    X_flags = np.array([flags['URL'], flags['EMAIL'], flags['PHONE'], flags['HTTP'], flags['HTTPS'], flags['BIT'], flags['WWW']]).reshape(1, -1)
    X_input = np.hstack((X_flags, X_input_text))

    return X_input

In [62]:
sms = "please stay at home. to encourage the notion of staying at home. all tax-paying citizens are entitled to �305.96 or more emergency refund. smsg.io/fcvbd"

In [63]:
mod = preprocess_new_text(sms)
clf = model.predict(mod)

In [64]:
print(clf)

[1]